# Deployment Configuration for Google ADK Agent Starter Kit

# Environment Settings
environment: production  # Options: development, staging, production

# Vertex AI Deployment Settings
vertex_ai:
  project_id: your-project-id
  region: us-central1
  machine_type: n1-standard-2
  min_replica_count: 1
  max_replica_count: 5
  accelerator_type: NVIDIA_TESLA_T4
  accelerator_count: 1

# Local Deployment Settings
local:
  host: 0.0.0.0
  port: 8000
  log_level: info
  reload: false

# Agent Settings
agent:
  type: search
  model: gemini-2.0-flash
  description: "Production search agent"
  instruction: "I can answer your questions by searching the internet. Just ask me anything!"

# Monitoring Settings
monitoring:
  enable_logging: true
  log_level: info
  enable_tracing: true
  enable_metrics: true

# Security Settings
security:
  enable_authentication: true
  authentication_type: api_key  # Options: api_key, oauth, jwt
  enable_rate_limiting: true
  rate_limit: 100  # Requests per minute
  enable_cors: true
  allowed_origins:
    - https://example.com
    - https://api.example.com

# Deployment Steps
deployment_steps:
  - name: Build deployment package
    command: python run.py build
  - name: Run tests
    command: python -m pytest
  - name: Deploy to Vertex AI
    command: python run.py deploy search --project {vertex_ai.project_id} --region {vertex_ai.region}
  - name: Verify deployment
    command: python run.py verify --endpoint {deployment_endpoint}
